### ISSUE TITLE
docker demo starts very slow.

### ISSUE THREAD

**Issue by rcemper** [evshvarov/i14y-csv#2]
reason:  launch of ISC Agent is not prevented at Container start.
````
i14y-csv-iris-1  | [INFO] Executing command /home/irisowner/irissys/startISCAgent.sh 2188...
i14y-csv-iris-1  | [INFO] Writing status to file: /home/irisowner/irissys/iscagent.status
i14y-csv-iris-1  | Reading configuration from file: /home/irisowner/irissys/iscagent.conf
i14y-csv-iris-1  | ISCAgent[17]: Starting
i14y-csv-iris-1  | ISCAgent[19]: Starting ApplicationServer on *:2188
i14y-csv-iris-1  | [INFO] ...executed command /home/irisowner/irissys/startISCAgent.sh 2188
---- not visible long hang ---
`````
use **--ISCAgent false**  as start parameter for iris-main

**Comment by evshvarov** [comment]
Wow. What is the new thing?

**Comment by rcemper** [comment]
since many months iris-community images start ISCAgent by default.
This is definitely nonsens if no MIRROR is involved.
**[my post in DC](https://community.intersystems.com/post/why-run-isc-agent-demo-docker)**
solution:     **command:** --check-caps false --ISCAgent false

another undocumented param iris-main
It is a default in my personal templates and was in my PR

**Comment by rcemper** [comment]
fixed

**Comment by evshvarov** [comment]
Thanks for revealing a new "hidden secret" of IRIS )
