### ISSUE TITLE
production fails: 1 more missing directory in repo

### ISSUE THREAD

**Issue by rcemper** [evshvarov/i14y-csv#4]
after manually adding the directory  /in to repo  production fails:
![image](https://user-images.githubusercontent.com/31236645/217951264-4da52f85-5985-41e7-aaea-bcca46467f64.png)
directory **/out** doesn't exist in repo out

**Comment by evshvarov** [comment]
Did you check out late changes? cannot reproduce the issue. Here is the directory: https://github.com/evshvarov/i14y-csv/blob/master/out/
and here is the setting in docker-compose:
https://github.com/evshvarov/i14y-csv/blob/b7b2997313dcd3cd7b5c9fb74d5f9af9f53ac553/docker-compose.yml
Here is the setting in production:
https://github.com/evshvarov/i14y-csv/blob/ae12783baba67cee3d2063fcde89ba0b123b8c43/src/esh/i14y/csv/F2CProduction.cls

**Comment by rcemper** [comment]
I have of course seen and used your recent changes. (also affects issue #3)
 you map your download directory is mapped to **/home/irisowner/irisdev**
 But you refer to **/home/irisowner/irisdev/in** and **/home/irisowner/irisdev/out**
 and none of these directories exists in your downloaded repo.
 and the production fails with **missing directory**
 might be your docker creates it at output (would be quite dangerous)
 but I fail to imagine that it also creates it by referencing the input directory
solution:
create /in and /out in your download directory manually after download 
and **before** the start of production.
Or more comfortable for the user add it to your repo as I did in my PR
For GitHub you need to place some empty dummy file inside as 
Github doesn't allow empty directories.

**Comment by evshvarov** [comment]
Ah, I see.
i have it in dev repo locally.
but they are empty and thus not
being committed as empty to GitHub.
will solve this.

**Comment by rcemper** [comment]
all fixed. works fine
